--- #YAML:1.0
name:                VMS-FindFile
version:             0.92
abstract:            Returns all file names matching a VMS wildcard specification.
license:             ~
author:              
    - Forrest Cahoon <forrest@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
